Enhancement/subplot layout adjustments
functime-org/functime pull request #181
Opened 2024-03-03 18:11 UTC by miroslaavi

## What does this implement/fix? Explain your changes.
This pull request introduces a new function _set_subplot_default_kwargs to dynamically set default plot sizes for subplots, enhancing the readability and aesthetics of plots in the plotting module. This function is now utilized in plot_panel, plot_forecasts, and plot_backtests to ensure consistent and optimal sizing of plots, especially when the user hasn't specified height and width in kwargs.

Additionally, this PR includes fixes in plot_panel and plot_backtests, similar to the improvements made in issue #179, ensuring consistency across plotting functions.

## Any other comments?

2024-03-05 19:44 UTC, miroslaavi commented
@baggiponte tagging you here as the first fixes are ready for review, looks like I am not able to add a reviewer yet. :)

2024-03-13 13:05 UTC, baggiponte commented
Sorry for the late reply. Still under pressure, will try to review this ASAP.

2024-03-13 23:00 UTC, baggiponte commented
Starting review, might still take a few days. First of all: excellent job, high quality comments, names and abstractions over repetitive stuff. Will leave some comments here and there.

I would kindly ask you to add some tests for the functions you added. Feel free to place them under a new `tests/test_plotting.py`.

2024-03-13 23:08 UTC, baggiponte commented
Kudos for removing `np.repeat` usage - that thing bugged me for waaay to much, but I never had the time to clean that up.

We do that "iterate over entities" at least three times in the module. Would you mind making that a standalone function and add tests? Of course, available to help. You don't need to test the tests, but make sure that the `divmod` vs `np.repeat` behaves the same.

2024-03-14 08:12 UTC, FBruzzesi reviewed
I am also giving a quick review, as @baggiponte called me in (I feel like a reviewer-ad-honorem 😂).

I left a minor suggestion - as such function has no facing api, but still good for standardization.

As @baggiponte mentioned, I aswell think there are other tiny code parts that can be refactored into a utility function.

Regarding unit tests, sadly I never had to test plotting functionalities.

2024-03-14 18:49 UTC, miroslaavi commented
Sounds great, thanks both for taking the time. I will look into these over the weekend!

2024-03-15 13:32 UTC, baggiponte commented
Thanks! One more thing: I updated main, could you rebase your PR? We'd prefer that to merging master, to keep a simpler commit history.

2024-03-15 21:38 UTC, miroslaavi commented
@baggiponte @FBruzzesi, I have now tried to module some of the repetitive code to own functions, but not sure what is the best way to deal with the small differences in plotting (naming, colors etc.). I've now added plot_params dict prior calling the "_add_scatter_traces_to_subplots".. maybe I just made it more complicated than it was haha :D 

I've tried with multiple different len series and columns and plotting looks to work well now with plot_panel, plot_forecast, and plot_backtests. I also added the tests to the test_plotting.py, have a look!

2024-03-16 10:51 UTC, miroslaavi commented
To add, I also tested some of the other plotting functions and noticed that the plots using plotly express doesn't work no more and leads to AssertionError. Not quite sure what causes it but most likely something changed either in plotly or polars. In order to make it work now, I rewrote the plot_entities to go.Figure instead, and for other plot functions made a quick fix and converting the polars DF to pandas prior plotting with .to_pandas()

2024-03-16 11:18 UTC, miroslaavi commented
> Thanks! One more thing: I updated main, could you rebase your PR? We'd prefer that to merging master, to keep a simpler commit history.

Cool, never done that prior as mostly used version history for my own projects that I was working alone. Also, noticed that my commit messages are not very constant or following a clear structure, so I'll check some best practices for that too. :)

Now it is like 10 commits for these changes, is it preferred to keep that way or is it ideal to squeeze in one commit for the merge?

2024-03-22 21:48 UTC, baggiponte commented
Ciao Miro, sorry for the late reply. Have a workshop tomorrow at EPFL. Should have time to review afterwards.

2024-03-23 06:36 UTC, miroslaavi commented
All good and take your time, have a great workshop! :)

2024-04-21 20:14 UTC, baggiponte requested changes
Thanks for the great work. One last thing: run the ruff and isort formatter and add the remaining type hints, then we can merge!

2024-04-21 20:14 UTC, baggiponte commented on functime/plotting.py
> +def _get_subplot_grid_position(i, n_cols):
Please add type hints 😊

2024-04-21 20:14 UTC, baggiponte commented on functime/plotting.py
> +def _prepare_data_for_subplots(y: Union[pl.DataFrame, pl.LazyFrame], n_series: int, last_n: int, seed: Union[int, None] = None):
Please add return types :)

2024-04-21 20:14 UTC, baggiponte commented on functime/plotting.py
> +    Tuple
Use `Tuple[<Dtype>, <Dtype>, <dtype>]` with appropriate types

2024-04-23 18:34 UTC, miroslaavi commented
@baggiponte, thanks! This was quite many changes in one PR, but going forward will raise issues and focus on smaller chunks. This is good to go from my side now.

2024-04-24 06:33 UTC, baggiponte commented
Amazing, will merge soon. Indeed it's a big PR but we requested most of the changes. Thank you very much for your contribution and patience 🫡

2024-04-27 09:45 UTC, merged